name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: 노드 설치 (Node.js 20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 의존성 설치
        run: npm install

      - name: 프로젝트 빌드
        run: npm run build

      - name: Git 설정
        if: github.event_name == 'push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 배포 주소 인증 설정
        if: github.event_name == 'push'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MY_DEPLOY_TOKEN }}@github.com/${{ github.repository }}.git

      - name: 프로젝트 배포
        if: github.event_name == 'push'
        run: npm run deploy
